[[redirects]]
  from = "/*"
  to = "/"
  status = 200


[[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"



[build]
command = “npm install && npm run build”
functions = “functions”
